"""
Dune Imperium Blend Builder - Web Version
Flask backend serving card data and blend management
"""

from flask import Flask, render_template, jsonify, request
from pathlib import Path
import openpyxl
import webbrowser
import threading

app = Flask(__name__)

# Global card data
ALL_CARDS = []


def load_cards_from_excel():
    """Load card data from Excel file."""
    excel_path = Path(__file__).parent / "Dune_Imperium_Card_Inventory.xlsx"

    if not excel_path.exists():
        raise FileNotFoundError(
            f"Could not find: {excel_path}\n\n"
            "Please ensure Dune_Imperium_Card_Inventory.xlsx is in the project directory."
        )

    wb = openpyxl.load_workbook(excel_path)
    ws = wb.active
    headers = [cell.value for cell in ws[1]]

    cards = []
    for row in ws.iter_rows(min_row=2, values_only=True):
        if not row[0]:
            continue

        row_dict = dict(zip(headers, row))
        card_name = str(row_dict.get("Card Name", "")).strip()
        if not card_name:
            continue

        source = str(row_dict.get("Source", "Base")).strip()
        card_set_mapping = {
            "Base": "base",
            "Ix": "ix",
            "Immortality": "immortality",
            "Uprising": "uprising",
            "Bloodlines": "bloodlines"
        }
        card_set = card_set_mapping.get(source, source.lower())

        def has_x(val):
            return val and str(val).strip().upper() == 'X'

        card = {
            "name": card_name,
            "card_set": card_set,
            "source": source,
            "count": int(float(row_dict.get("Count") or 1)),
            "cost": str(row_dict.get("Persuasion Cost") or "0"),
            "agent_ability": row_dict.get("Agent Ability") or "",
            "acquisition_bonus": row_dict.get("Acquisition Bonus") or "",
            "reveal_persuasion": str(row_dict.get("Reveal Persuasion") or "0"),
            "reveal_swords": str(row_dict.get("Reveal Swords") or "0"),
            "reveal_ability": row_dict.get("Reveal Ability") or "",
            "passive_ability": row_dict.get("Passive Ability") or "",
            "tech": row_dict.get("Tech") or "",
            "shipping": row_dict.get("Shipping") or "",
            "unload": row_dict.get("Unload") or "",
            "infiltration": row_dict.get("Infiltration") or "",
            "research": row_dict.get("Research") or "",
            "grafting": row_dict.get("Grafting") or "",
            "spies": row_dict.get("Spies") or "",
            "sandworms": row_dict.get("Sandworms") or "",
            "contracts": row_dict.get("Contracts") or "",
            "battle_icons": row_dict.get("Battle Icons") or "",
            "sardaukar": row_dict.get("Sardaukar") or "",
            "compatibility": str(row_dict.get("Compatibility", "All") or "All"),
            "vps_available": str(row_dict.get("VPs Available") or "0"),
            "green_access": has_x(row_dict.get("Green Access")),
            "purple_access": has_x(row_dict.get("Purple Access")),
            "yellow_access": has_x(row_dict.get("Yellow Access")),
            "emperor_access": has_x(row_dict.get("Emperor Access")),
            "spacing_guild_access": has_x(row_dict.get("Spacing Guild Access")),
            "bene_gesserit_access": has_x(row_dict.get("Bene Gesserit Access")),
            "fremen_access": has_x(row_dict.get("Fremen Access")),
            "spy_access": has_x(row_dict.get("Spy Access")),
        }
        cards.append(card)

    print(f"Loaded {len(cards)} cards")
    return cards


@app.route('/')
def index():
    """Serve the main page."""
    return render_template('index.html')


@app.route('/api/cards')
def get_cards():
    """Return all cards as JSON."""
    return jsonify(ALL_CARDS)


@app.route('/api/deck/save', methods=['POST'])
def save_deck():
    """Save deck to markdown file."""
    data = request.json
    deck_name = data.get('name', 'Untitled Blend')
    cards = data.get('cards', [])

    md = f"# {deck_name}\n\n"
    md += f"**Total Cards:** {len(cards)}\n\n"

    by_set = {}
    for card in cards:
        card_set = card['card_set']
        if card_set not in by_set:
            by_set[card_set] = []
        by_set[card_set].append(card)

    for card_set in sorted(by_set.keys()):
        set_cards = by_set[card_set]
        set_name_map = {
            'base': 'Base Game',
            'ix': 'Rise of Ix',
            'immortality': 'Immortality',
            'uprising': 'Uprising',
            'bloodlines': 'Bloodlines'
        }
        set_name = set_name_map.get(card_set, card_set.capitalize())

        md += f"## {set_name}\n\n"
        for card in set_cards:
            md += f"- **{card['name']}** (Cost: {card['cost']})\n"
        md += "\n"

    md += "---\n*Generated by Dune Imperium Deck Builder*\n"

    filename = f"{deck_name}.md".replace(' ', '_').replace('/', '_')
    filepath = Path(__file__).parent / filename

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(md)

    return jsonify({"success": True, "filepath": str(filepath)})


def open_browser():
    """Open browser after short delay."""
    webbrowser.open('http://localhost:5000')


if __name__ == '__main__':
    ALL_CARDS = load_cards_from_excel()
    threading.Timer(1.5, open_browser).start()
    app.run(debug=False, port=5000)

